import { apiClient } from './api';

export const adminPhase1API = {
  bootstrap: () => apiClient.post('/admin/core/bootstrap'),
  dashboard: (params = {}) => apiClient.get('/admin/core/dashboard', { params }),
  users: (params = {}) => apiClient.get('/admin/core/users', { params }),
  createUser: (payload) => apiClient.post('/admin/core/users', payload),
  updateUser: (userId, payload) => apiClient.patch(`/admin/core/users/${userId}`, payload),
  deleteUser: (userId) => apiClient.delete(`/admin/core/users/${userId}`),
  branchFranchise: () => apiClient.get('/admin/core/branch-franchise'),
  createBranch: (payload) => apiClient.post('/admin/core/branches', payload),
  createFranchise: (payload) => apiClient.post('/admin/core/franchises', payload),
  updateBranch: (code, payload) => apiClient.put(`/admin/core/branches/${encodeURIComponent(code)}`, payload),
  updateFranchise: (code, payload) => apiClient.put(`/admin/core/franchises/${encodeURIComponent(code)}`, payload),
  deleteBranch: (code, payload) => apiClient.post(`/admin/core/branches/${encodeURIComponent(code)}/delete`, payload),
  deleteFranchise: (code, payload) => apiClient.post(`/admin/core/franchises/${encodeURIComponent(code)}/delete`, payload),
  updateUserStatus: (userId, payload) => apiClient.patch(`/admin/core/users/${userId}/status`, payload),
  resetUserPassword: (userId, payload) => apiClient.post(`/admin/core/users/${userId}/reset-password`, payload),
  userAuditLogs: (userId) => apiClient.get(`/admin/core/users/${userId}/audit-logs`),
  roles: () => apiClient.get('/admin/core/roles'),
  permissions: () => apiClient.get('/admin/core/permissions'),
  createRole: (payload) => apiClient.post('/admin/core/roles', payload),
  updateRole: (roleId, payload) => apiClient.put(`/admin/core/roles/${roleId}`, payload),
  updateRoleStatus: (roleId, payload) => apiClient.patch(`/admin/core/roles/${roleId}/status`, payload),
  deleteRole: (roleId) => apiClient.delete(`/admin/core/roles/${roleId}`),
  bulkDeleteRoles: (roleIds) => apiClient.post('/admin/core/roles/bulk-delete', { role_ids: roleIds }),
  assignAccess: (userId, payload) => apiClient.post(`/admin/core/users/${userId}/assign-access`, payload),
  protectedAccounts: () => apiClient.get('/admin/core/protected-accounts'),
  accessHistory: () => apiClient.get('/admin/core/access-history'),
  reportingHierarchy: () => apiClient.get('/admin/core/reporting-hierarchy'),
  saveReportingRelation: (payload) => apiClient.post('/admin/core/reporting-relations', payload),
  transferEmployee: (payload) => apiClient.post('/admin/core/reporting-hierarchy/transfer', payload),
  reportingHistory: (userId) => apiClient.get(`/admin/core/reporting-hierarchy/${userId}/history`),
  escalationRules: () => apiClient.get('/admin/core/escalation-rules'),
  createEscalationRule: (payload) => apiClient.post('/admin/core/escalation-rules', payload),
  updateEscalationRule: (ruleId, payload) => apiClient.put(`/admin/core/escalation-rules/${ruleId}`, payload),
  updateEscalationRuleStatus: (ruleId, payload) => apiClient.patch(`/admin/core/escalation-rules/${ruleId}/status`, payload),
  slaPolicies: () => apiClient.get('/admin/core/sla-policies'),
  createSlaPolicy: (payload) => apiClient.post('/admin/core/sla-policies', payload),
  updateSlaPolicy: (policyId, payload) => apiClient.put(`/admin/core/sla-policies/${policyId}`, payload),
  activeEscalations: () => apiClient.get('/admin/core/active-escalations'),
  escalationHistory: () => apiClient.get('/admin/core/escalation-history'),
  notificationRules: () => apiClient.get('/admin/core/notification-rules'),
  createNotificationRule: (payload) => apiClient.post('/admin/core/notification-rules', payload),
  updateNotificationRule: (ruleId, payload) => apiClient.put(`/admin/core/notification-rules/${ruleId}`, payload),
  updateNotificationRuleStatus: (ruleId, payload) => apiClient.patch(`/admin/core/notification-rules/${ruleId}/status`, payload),
  auditLogs: (params = {}) => apiClient.get('/admin/core/audit-logs', { params }),
  exportAuditLogs: (params = {}) => apiClient.get('/admin/core/audit-logs/export-csv', { params, responseType: 'blob' }),
  hosts: (params = {}) => apiClient.get('/admin/core/hosts', { params }),
  hostKycDetail: (hostId) => apiClient.get(`/admin/core/hosts/${hostId}/kyc`),
  updateHostKyc: (hostId, payload) => apiClient.patch(`/admin/core/hosts/${hostId}/kyc`, payload),
  updateHostKycDocument: (hostId, payload) => apiClient.patch(`/admin/core/hosts/${hostId}/kyc/document`, payload),
  updateHostBankVerification: (hostId, payload) => apiClient.patch(`/admin/core/hosts/${hostId}/kyc/bank`, payload),
  updateHostAgreementVerification: (hostId, payload) => apiClient.patch(`/admin/core/hosts/${hostId}/kyc/agreement`, payload),
  requestHostKycReupload: (hostId, payload) => apiClient.post(`/admin/core/hosts/${hostId}/kyc/request-reupload`, payload),
  assignHostTeam: (hostId, payload) => apiClient.post(`/admin/core/hosts/${hostId}/assign`, payload),
  propertyOperations: (params = {}) => apiClient.get('/admin/core/properties-operations', { params }),
  propertyOperationDetail: (propertyId) => apiClient.get(`/admin/core/properties-operations/${propertyId}`),
  assignPropertyTeam: (propertyId, payload) => apiClient.post(`/admin/core/properties-operations/${propertyId}/assign`, payload),
  updatePropertyChecklist: (propertyId, payload) => apiClient.patch(`/admin/core/properties-operations/${propertyId}/checklist`, payload),
  updatePropertyStage: (propertyId, payload) => apiClient.patch(`/admin/core/properties-operations/${propertyId}/stage`, payload),
  updatePropertyOperationStatus: (propertyId, payload) => apiClient.patch(`/admin/core/properties-operations/${propertyId}/status`, payload),
  updatePropertyBoost: (propertyId, payload) => apiClient.patch(`/admin/core/properties-operations/${propertyId}/boost`, payload),
  deletePropertyOperation: (propertyId, payload) => apiClient.post(`/properties/${propertyId}/delete`, payload),
  exportUsers: (params = {}) => apiClient.get('/admin/users/export-csv', { params, responseType: 'blob' }),
  subscriptions: (params = {}) => apiClient.get('/admin/core/subscriptions', { params }),
  subscriptionPlans: () => apiClient.get('/admin/core/subscription-plans'),
  createSubscriptionPlan: (payload) => apiClient.post('/subscriptions/admin/plans', null, { params: payload }),
  updateSubscriptionPlan: (planId, payload) => apiClient.put(`/subscriptions/admin/plans/${planId}`, null, { params: payload }),
  deleteSubscriptionPlan: (planId) => apiClient.delete(`/subscriptions/admin/plans/${planId}`),
  updateSubscriptionStatus: (subscriptionId, payload) => apiClient.patch(`/admin/core/subscriptions/${subscriptionId}/status`, payload),
  deleteSubscription: async (subscriptionId, payload) => {
    try {
      return await apiClient.post(`/admin/core/subscriptions/${subscriptionId}/delete`, payload);
    } catch (error) {
      if (error.response?.status === 405) {
        return apiClient.delete(`/admin/core/subscriptions/${subscriptionId}`, { data: payload });
      }
      throw error;
    }
  },
  updateSubscriptionPlanStatus: (planId, payload) => apiClient.patch(`/admin/core/subscription-plans/${planId}/status`, payload),
  bookingOperations: (params = {}) => apiClient.get('/admin/core/bookings', { params }),
  bookingOperationDetail: (bookingId) => apiClient.get(`/admin/core/bookings/${bookingId}`),
  updateBookingOperationStatus: (bookingId, payload) => apiClient.patch(`/admin/core/bookings/${bookingId}/status`, payload),
  financeOverview: () => apiClient.get('/admin/account/overview'),
  financeMrrChart: (params = {}) => apiClient.get('/admin/account/mrr-chart', { params }),
  financeTransactions: (params = {}) => apiClient.get('/admin/account/transactions', { params }),
  exportFinanceTransactions: (params = {}) => apiClient.get('/admin/account/transactions/export-csv', { params, responseType: 'blob' }),
  shareFinanceInvoice: (transactionId, channel) => apiClient.post(`/admin/account/transactions/${transactionId}/share-invoice`, { channel }),
  financePayouts: (params = {}) => apiClient.get('/admin/account/payouts', { params }),
  processFinancePayout: (payoutId, payload = {}) => apiClient.post(`/admin/account/payouts/${payoutId}/process`, payload),
  sweepFinancePayoutEligibility: () => apiClient.post('/admin/account/payouts/sweep-eligibility'),
  processEligibleFinancePayouts: () => apiClient.post('/admin/account/payouts/process-eligible'),
  runAutoFinancePayouts: () => apiClient.post('/admin/account/payouts/run-auto'),
  financeRefunds: (params = {}) => apiClient.get('/admin/account/refunds', { params }),
  initiateFinanceRefund: (bookingId, payload) => apiClient.post(`/admin/account/refunds/${bookingId}`, payload),
  approveFinanceRefund: (refundId, payload = {}) => apiClient.post(`/admin/account/refunds/${refundId}/approve`, payload),
  rejectFinanceRefund: (refundId, payload = {}) => apiClient.post(`/admin/account/refunds/${refundId}/reject`, payload),
  financeRefundPolicyPreview: (params = {}) => apiClient.get('/admin/account/refunds/policy-preview', { params }),
  financePayoutAutoStatus: () => apiClient.get('/admin/account/payouts/auto-status'),
  financeTaxCommission: () => apiClient.get('/admin/core/finance/tax-commission'),
  paymentConfig: () => apiClient.get('/bookings/payment/config'),
  updatePaymentConfig: (payload) => apiClient.put('/bookings/admin/payment/config', payload),
  bookingTaxSlabs: () => apiClient.get('/admin/core/settings/booking-tax-slabs'),
  createBookingTaxSlab: (payload) => apiClient.post('/admin/core/settings/booking-tax-slabs', payload),
  updateBookingTaxSlab: (slabId, payload) => apiClient.put(`/admin/core/settings/booking-tax-slabs/${slabId}`, payload),
  updateBookingTaxSlabStatus: (slabId, payload) => apiClient.patch(`/admin/core/settings/booking-tax-slabs/${slabId}/status`, payload),
  deleteBookingTaxSlab: (slabId, payload = {}) => apiClient.delete(`/admin/core/settings/booking-tax-slabs/${slabId}`, { data: payload }),
  tdsConfig: () => apiClient.get('/admin/core/settings/tds'),
  updateTdsConfig: (payload) => apiClient.put('/admin/core/settings/tds', payload),
  hostPayoutPreview: (payload) => apiClient.post('/admin/core/settings/host-payout-preview', payload),
  crmDashboard: (params = {}) => apiClient.get('/admin/core/crm/dashboard', { params }),
  crmLeads: (params = {}) => apiClient.get('/admin/core/crm/leads', { params }),
  updateCrmLead: (leadId, payload) => apiClient.patch(`/admin/core/crm/leads/${leadId}`, payload),
  crmAssignees: () => apiClient.get('/admin/core/crm/assignees'),
  assignCrmLead: (leadId, payload) => apiClient.post(`/admin/core/crm/leads/${leadId}/assign`, payload),
  crmPipeline: () => apiClient.get('/admin/core/crm/pipeline'),
  updateCrmPipeline: (leadId, payload) => apiClient.patch(`/admin/core/crm/leads/${leadId}/pipeline`, payload),
  crmReports: () => apiClient.get('/admin/core/crm/reports'),
  communicationOverview: () => apiClient.get('/admin/core/communication/overview'),
  communicationNotifications: (params = {}) => apiClient.get('/admin/core/communication/notifications', { params }),
  sendCommunicationTest: (payload) => apiClient.post('/admin/core/communication/notifications/test', payload),
  communicationDeliveryAudit: () => apiClient.get('/admin/core/communication/delivery-audit'),
  supportOverview: () => apiClient.get('/admin/core/support/overview'),
  supportAssignees: () => apiClient.get('/admin/core/support/assignees'),
  supportReports: () => apiClient.get('/admin/core/support/reports'),
  assignSupportTicket: (ticketId, payload) => apiClient.post(`/admin/core/support/tickets/${ticketId}/assign`, payload),
  platformSettingsOverview: () => apiClient.get('/admin/core/settings/overview'),
  updateSecuritySettings: (payload) => apiClient.put('/admin/core/settings/security', payload),
  operationalSettings: () => apiClient.get('/admin/core/settings/operations'),
  updateOperationalSettings: (payload) => apiClient.put('/admin/core/settings/operations', payload),
  analyticsOverview: (params = {}) => apiClient.get('/admin/core/analytics/overview', { params }),
  exportAnalytics: (params = {}) => apiClient.get('/admin/core/analytics/export-csv', { params, responseType: 'blob' }),
};
